package utils

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// CreateDirectory creates a directory if it doesn't exist
func CreateDirectory(path string) error {
	if err := os.MkdirAll(path, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", path, err)
	}
	return nil
}

// FileExists checks if a file exists
func FileExists(path string) bool {
	_, err := os.Stat(path)
	return !os.IsNotExist(err)
}

// DirectoryExists checks if a directory exists
func DirectoryExists(path string) bool {
	info, err := os.Stat(path)
	if os.IsNotExist(err) {
		return false
	}
	return info.IsDir()
}

// WriteFile writes content to a file
func WriteFile(path, content string) error {
	// Ensure directory exists
	dir := filepath.Dir(path)
	if err := CreateDirectory(dir); err != nil {
		return err
	}

	// Write file
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", path, err)
	}
	return nil
}

// ReadFile reads content from a file
func ReadFile(path string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("failed to read file %s: %w", path, err)
	}
	return string(content), nil
}

// DeleteFile deletes a file if it exists
func DeleteFile(path string) error {
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("failed to delete file %s: %w", path, err)
	}
	return nil
}

// CopyFile copies a file from source to destination
func CopyFile(src, dst string) error {
	// Read source file
	content, err := ReadFile(src)
	if err != nil {
		return err
	}

	// Write to destination
	return WriteFile(dst, content)
}

// ListFiles lists all files in a directory with a specific extension
func ListFiles(dir, ext string) ([]string, error) {
	var files []string
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ext) {
			files = append(files, path)
		}
		return nil
	})
	return files, err
}

// GetRelativePath returns the relative path from base to target
func GetRelativePath(base, target string) (string, error) {
	relPath, err := filepath.Rel(base, target)
	if err != nil {
		return "", fmt.Errorf("failed to get relative path: %w", err)
	}
	return relPath, nil
}

// CleanPath cleans a file path
func CleanPath(path string) string {
	return filepath.Clean(path)
}

// JoinPath joins path elements
func JoinPath(elem ...string) string {
	return filepath.Join(elem...)
}

// IsGoCloudGenerated checks if a file was generated by GoCloud CLI
func IsGoCloudGenerated(filePath string) bool {
	content, err := os.ReadFile(filePath)
	if err != nil {
		return false
	}

	// Check for GoCloud CLI signature
	return strings.Contains(string(content), "This file is generated and maintained by GoCloud CLI")
}
