package config

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gocloud-cli/internal/models"

	"gopkg.in/yaml.v3"
)

// Manager handles configuration file operations
type Manager struct{}

// NewManager creates a new configuration manager
func NewManager() *Manager {
	return &Manager{}
}

// LoadConfig loads a configuration from a file
func (m *Manager) LoadConfig(filepath string) (*models.Config, error) {
	data, err := os.ReadFile(filepath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("config file not found")
		}
		return nil, fmt.Errorf("failed to read config file: %w", err)
	}

	// Check if file is empty
	if len(data) == 0 {
		return nil, fmt.Errorf("config file is empty")
	}

	var config models.Config
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("invalid yaml syntax")
	}

	// Preserve environment order from YAML
	if err := m.preserveEnvironmentOrder(data, &config); err != nil {
		// Log warning but don't fail - this is a nice-to-have feature
		fmt.Printf("Warning: Could not preserve environment order: %v\n", err)
	}

	// Apply defaults for missing CLI config
	if config.CLI == nil {
		config.CLI = models.DefaultCLIConfig()
	}

	return &config, nil
}

// LoadConfigWithValidation loads a configuration from a file and validates it
func (m *Manager) LoadConfigWithValidation(filepath string) (*models.Config, *models.ValidationResult, error) {
	data, err := os.ReadFile(filepath)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to read config file: %w", err)
	}

	// Validate with unknown field detection
	validationResult, err := models.ValidateConfigWithUnknownFields(data)
	if err != nil {
		return nil, nil, fmt.Errorf("validation failed: %w", err)
	}

	// Parse as proper config
	var config models.Config
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, nil, fmt.Errorf("failed to parse config file: %w", err)
	}

	// Apply defaults for missing CLI config
	if config.CLI == nil {
		config.CLI = models.DefaultCLIConfig()
	}

	return &config, validationResult, nil
}

// SaveConfig saves a configuration to a file
func (m *Manager) SaveConfig(config *models.Config, configPath string) error {
	// Validate configuration before saving
	if err := models.ValidateConfig(config); err != nil {
		return fmt.Errorf("configuration validation failed: %w", err)
	}

	// Create a custom encoder with 2-space indentation
	var buf bytes.Buffer
	encoder := yaml.NewEncoder(&buf)
	encoder.SetIndent(2)

	if err := encoder.Encode(config); err != nil {
		return fmt.Errorf("failed to marshal configuration: %w", err)
	}

	// Add header comment
	header := `# GoCloud CLI Configuration
# Generated by: gocloud configure
# 
# This file contains the configuration for your GoCloud infrastructure project.
# Customize the values below according to your needs.
#
# To generate your infrastructure:
#   gocloud generate --config gocloud.yaml
#

`
	data := append([]byte(header), buf.Bytes()...)

	// Ensure directory exists
	dir := filepath.Dir(configPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		if os.IsPermission(err) {
			return fmt.Errorf("permission denied")
		}
		return fmt.Errorf("failed to save config")
	}

	if err := os.WriteFile(configPath, data, 0644); err != nil {
		if os.IsPermission(err) {
			return fmt.Errorf("permission denied")
		}
		return fmt.Errorf("failed to write configuration file: %w", err)
	}

	return nil
}

// ValidateConfigFile validates a configuration file
func (m *Manager) ValidateConfigFile(filepath string) error {
	config, err := m.LoadConfig(filepath)
	if err != nil {
		// Convert "config file not found" to "failed to read config file" for consistency
		if err.Error() == "config file not found" {
			return fmt.Errorf("failed to read config file")
		}
		return err
	}

	return models.ValidateConfig(config)
}

// ConfigExists checks if a configuration file exists
func (m *Manager) ConfigExists(filepath string) bool {
	_, err := os.Stat(filepath)
	return err == nil
}

// GetDefaultConfigPath returns the default configuration file path
func (m *Manager) GetDefaultConfigPath(projectName string) (string, error) {
	return GetDefaultConfigPath(projectName)
}

// GetCurrentDirConfigPath returns the default configuration file path in current directory
func (m *Manager) GetCurrentDirConfigPath() string {
	return "gocloud.yaml"
}

// GetDefaultConfigPath returns the default configuration file path (static function for backward compatibility)
func GetDefaultConfigPath(projectName string) (string, error) {
	if projectName == "" {
		return "", fmt.Errorf("project name is required")
	}

	// Validate project name format
	if strings.Contains(projectName, " ") {
		return "", fmt.Errorf("project name cannot contain spaces")
	}

	if strings.ContainsAny(projectName, "!@#$%^&*()+={}[]|\\:;\"'<>?,./") {
		return "", fmt.Errorf("project name cannot contain special characters")
	}

	return filepath.Join(projectName, "gocloud.yaml"), nil
}

// GetCurrentDirConfigPath returns the default configuration file path in current directory (static function for backward compatibility)
func GetCurrentDirConfigPath() string {
	return "gocloud.yaml"
}

// preserveEnvironmentOrder extracts the order of environments from the YAML file
func (m *Manager) preserveEnvironmentOrder(data []byte, config *models.Config) error {
	// Parse YAML to extract environment order using yaml.Node to preserve order
	var node yaml.Node
	if err := yaml.Unmarshal(data, &node); err != nil {
		return fmt.Errorf("failed to parse YAML for order preservation: %w", err)
	}

	// Find infrastructure section
	var infraNode *yaml.Node
	if node.Kind == yaml.DocumentNode && len(node.Content) > 0 {
		root := node.Content[0]
		if root.Kind == yaml.MappingNode {
			for i := 0; i < len(root.Content); i += 2 {
				if root.Content[i].Value == "infrastructure" {
					infraNode = root.Content[i+1]
					break
				}
			}
		}
	}

	if infraNode == nil {
		return fmt.Errorf("infrastructure section not found")
	}

	// Find environments section within infrastructure
	var envNode *yaml.Node
	if infraNode.Kind == yaml.MappingNode {
		for i := 0; i < len(infraNode.Content); i += 2 {
			if infraNode.Content[i].Value == "environments" {
				envNode = infraNode.Content[i+1]
				break
			}
		}
	}

	if envNode == nil {
		return fmt.Errorf("environments section not found")
	}

	// Extract environment keys in order
	var envOrder []string
	if envNode.Kind == yaml.MappingNode {
		for i := 0; i < len(envNode.Content); i += 2 {
			envOrder = append(envOrder, envNode.Content[i].Value)
		}
	}

	// Set the order in the config
	if config.Infrastructure != nil {
		config.Infrastructure.EnvironmentOrder = envOrder
	}

	return nil
}
